require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DiscussionCommentsController do

  # This should return the minimal set of attributes required to create a valid
  # DiscussionComment. As you add validations to DiscussionComment, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "comment" => "MyText" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DiscussionCommentsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all discussion_comments as @discussion_comments" do
      discussion_comment = DiscussionComment.create! valid_attributes
      get :index, {}, valid_session
      assigns(:discussion_comments).should eq([discussion_comment])
    end
  end

  describe "GET show" do
    it "assigns the requested discussion_comment as @discussion_comment" do
      discussion_comment = DiscussionComment.create! valid_attributes
      get :show, {:id => discussion_comment.to_param}, valid_session
      assigns(:discussion_comment).should eq(discussion_comment)
    end
  end

  describe "GET new" do
    it "assigns a new discussion_comment as @discussion_comment" do
      get :new, {}, valid_session
      assigns(:discussion_comment).should be_a_new(DiscussionComment)
    end
  end

  describe "GET edit" do
    it "assigns the requested discussion_comment as @discussion_comment" do
      discussion_comment = DiscussionComment.create! valid_attributes
      get :edit, {:id => discussion_comment.to_param}, valid_session
      assigns(:discussion_comment).should eq(discussion_comment)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new DiscussionComment" do
        expect {
          post :create, {:discussion_comment => valid_attributes}, valid_session
        }.to change(DiscussionComment, :count).by(1)
      end

      it "assigns a newly created discussion_comment as @discussion_comment" do
        post :create, {:discussion_comment => valid_attributes}, valid_session
        assigns(:discussion_comment).should be_a(DiscussionComment)
        assigns(:discussion_comment).should be_persisted
      end

      it "redirects to the created discussion_comment" do
        post :create, {:discussion_comment => valid_attributes}, valid_session
        response.should redirect_to(DiscussionComment.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved discussion_comment as @discussion_comment" do
        # Trigger the behavior that occurs when invalid params are submitted
        DiscussionComment.any_instance.stub(:save).and_return(false)
        post :create, {:discussion_comment => { "comment" => "invalid value" }}, valid_session
        assigns(:discussion_comment).should be_a_new(DiscussionComment)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        DiscussionComment.any_instance.stub(:save).and_return(false)
        post :create, {:discussion_comment => { "comment" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested discussion_comment" do
        discussion_comment = DiscussionComment.create! valid_attributes
        # Assuming there are no other discussion_comments in the database, this
        # specifies that the DiscussionComment created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        DiscussionComment.any_instance.should_receive(:update_attributes).with({ "comment" => "MyText" })
        put :update, {:id => discussion_comment.to_param, :discussion_comment => { "comment" => "MyText" }}, valid_session
      end

      it "assigns the requested discussion_comment as @discussion_comment" do
        discussion_comment = DiscussionComment.create! valid_attributes
        put :update, {:id => discussion_comment.to_param, :discussion_comment => valid_attributes}, valid_session
        assigns(:discussion_comment).should eq(discussion_comment)
      end

      it "redirects to the discussion_comment" do
        discussion_comment = DiscussionComment.create! valid_attributes
        put :update, {:id => discussion_comment.to_param, :discussion_comment => valid_attributes}, valid_session
        response.should redirect_to(discussion_comment)
      end
    end

    describe "with invalid params" do
      it "assigns the discussion_comment as @discussion_comment" do
        discussion_comment = DiscussionComment.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DiscussionComment.any_instance.stub(:save).and_return(false)
        put :update, {:id => discussion_comment.to_param, :discussion_comment => { "comment" => "invalid value" }}, valid_session
        assigns(:discussion_comment).should eq(discussion_comment)
      end

      it "re-renders the 'edit' template" do
        discussion_comment = DiscussionComment.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DiscussionComment.any_instance.stub(:save).and_return(false)
        put :update, {:id => discussion_comment.to_param, :discussion_comment => { "comment" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested discussion_comment" do
      discussion_comment = DiscussionComment.create! valid_attributes
      expect {
        delete :destroy, {:id => discussion_comment.to_param}, valid_session
      }.to change(DiscussionComment, :count).by(-1)
    end

    it "redirects to the discussion_comments list" do
      discussion_comment = DiscussionComment.create! valid_attributes
      delete :destroy, {:id => discussion_comment.to_param}, valid_session
      response.should redirect_to(discussion_comments_url)
    end
  end

end
